default:
  image: ruby:3.2

pages:
  script:
    - mkdir .public
    - cp -r public/* .public/
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - main